version: '3.8'
services:
  freelancechain:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/twitter-bot
    environment:
      - service=freelancechain
    ports:
      - 80:80
      