version: '3.8'
services:
  freelancechain:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/twitter-bot
    environment:
      - service=freelancechain
  tweeter-id:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/twitter-bot
    environment:
      - service=tweeter-id
      